Update utp

diff --git a/utp b/utp
--- a/utp
+++ b/utp
@@ -3,6 +3,7 @@
 OpenVPN_Port1='1103'
 OpenVPN_Port2='25222' # take note when you change this port, openvpn sun noload config will not work
 OvpnDownload_Port='81' # Before changing this value, please read this document. It contains all unsafe ports for Google Chrome Browser, please read from line #23 to line #89: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc
+Ohp_Port='7752'
 # Server local time
 MyVPS_Time='Asia/Kuala_Lumpur'
 #############################
@@ -532,8 +533,9 @@ cat <<EOF152> /var/www/openvpn/tcp.ovpn
 # Credits to GakodX
 client
 dev tun
-remote $IPADDR $OpenVPN_Port1 tcp
-http-proxy $(curl -s http://ipinfo.io/ip || wget -q http://ipinfo.io/ip) $Proxy_Port
+proto tcp
+remote $IPADDR $OpenVPN_Port1
+http-proxy $(curl -s http://ipinfo.io/ip || wget -q http://ipinfo.io/ip) $Ohp_Port
 resolv-retry infinite
 route-method exe
 resolv-retry infinite
@@ -715,16 +717,168 @@ chmod +x /usr/bin/*
 sed -i $MYIP2 /usr/bin/user-add-pptp;
 rm bashmenu.zip
 
+
+clear
+DISTRO=`awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }'`
+SERVER_IP=`ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'`
+
+# Welcome Message
+echo 'Welcome to WhyTzy96 Script'
+echo 'Script Version: 0.1'
+echo 'Updated on: 07/08/2021'
+
+# Verify Distro
+if ! [[ $DISTRO == "ubuntu" || $DISTRO == "debian" ]]; then
+	echo 'This script works only on Debian/Ubuntu OS'
+	exit 1
+fi
+
+# Check if root
+if [ "$(id -u)" != "0" ]; then
+   echo "This script must be run as root" 1>&2
+   exit 1
+fi
+
+
+if test -f "/root/.tcat_installed"; then
+	echo 'TunnelCat VPN Software already installed!'
+	exit 1
+fi
+
+#PORT SERVER
+read -e -p 'Input your Server IP: ' -i $SERVER_IP SERVER_IP
+read -e -p 'Input OpenVPN TCP Port: ' -i '1103' OPENVPN_PORT
+read -e -p 'Input Privoxy Port: ' -i '8080' PRIVOXY_PORT
+read -e -p 'Input ohpserver Port: ' -i '7752' OHP_PORT
+read -e -p 'Input stunnel Port: ' -i '443' STUNNEL_PORT
+read -e -p 'Input DNS Tunnel Domain: ' -i 'dns.tunnel.example.com' DNS_TUNNEL_DOMAIN
+
+# Check input
+echo 'Checking Input...'
+if ! [[ $SERVER_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+	echo 'Server IP is invalid'
+	exit 1
+fi
+
+if ! [[ $OPENVPN_PORT =~ ^[0-9]+$ || $OHP_PORT =~ ^[0-9]+$ || $PRIVOXY_PORT =~ ^[0-9]+$ || $STUNNEL_PORT =~ ^[0-9]+$ ]]; then
+	echo 'Port is invalid'
+	exit 1
+fi
+
+echo 'Proceeding with the installation of dependencies'
+
+# Install Dependencies
+echo 'Installing Dependencies'
+DEBIAN_FRONTEND=noninteractive apt install -y resolvconf privoxy stunnel unzip iproute2 dns2tcp
+echo 'Dependencies Installed!' 
+
+# Install TunnelCat VPN Software
+echo 'Installing ohpserver'
+wget https://github.com/lfasmpao/open-http-puncher/releases/download/0.1/ohpserver-linux32.zip
+unzip ohpserver-linux32.zip
+rm ohpserver-linux32.zip
+mv ohpserver /usr/local/bin/
+chmod +x /usr/local/bin/ohpserver
+
+# Setup Privoxy
+echo 'Setting up Privoxy'
+mkdir /etc/privoxy/
+cat <<EOF > /etc/privoxy/config
+user-manual /usr/share/doc/privoxy/user-manual
+confdir /etc/privoxy
+logdir /var/log/privoxy
+actionsfile match-all.action
+actionsfile default.action
+actionsfile user.action
+filterfile default.filter
+filterfile user.filter
+logfile logfile
+listen-address  :$PRIVOXY_PORT
+toggle 1
+enable-remote-toggle  0
+enable-remote-http-toggle  0
+enable-edit-actions 0
+enforce-blocks 0
+buffer-limit 4096
+enable-proxy-authentication-forwarding 0
+forwarded-connect-retries  0
+accept-intercepted-requests 0
+allow-cgi-request-crunching 0
+split-large-forms 0
+keep-alive-timeout 5
+tolerate-pipelining 1
+socket-timeout 300
+EOF
+
+cat <<EOF1 > /etc/privoxy/user.action
+{ +block }
+/
+{ -block }
+*.tcat.me
+127.0.0.1
+$SERVER_IP
+EOF1
+
+# Setup ohpserver
+echo 'Setup ohpserver'
+cat <<EOF > /etc/systemd/system/ohpserver.service
+[Unit]
+Description=Daemonize OpenHTTP Puncher Server
+Wants=network.target
+After=network.target
+[Service]
+ExecStart=/usr/local/bin/ohpserver -port $OHP_PORT -proxy 127.0.0.1:$PRIVOXY_PORT -tunnel $SERVER_IP:$OPENVPN_PORT
+Restart=always
+RestartSec=3
+[Install]
+WantedBy=multi-user.target
+EOF
+
+echo 'Setup dns2tcp'
+cat <<EOF > /etc/dns2tcpd.conf
+listen = 0.0.0.0
+port = 53
+user = nobody
+chroot = /tmp
+pid_file = /var/run/dns2tcp.pid
+domain = $DNS_TUNNEL_DOMAIN
+resources = ovpn:$SERVER_IP:$OPENVPN_PORT
+EOF
+
+# Start Services
+echo 'Running Services'
+echo "nameserver 8.8.8.8" > /etc/resolvconf/resolv.conf.d/head
+systemctl daemon-reload
+systemctl restart resolvconf
+systemctl restart stunnel4
+systemctl restart privoxy
+systemctl start ohpserver
+systemctl stop systemd-resolved
+systemctl start dns2tcp
+
+# Enable on boot
+echo 'Start services on boot'
+systemctl enable stunnel4
+systemctl enable privoxy
+systemctl enable dns2tcp
+systemctl enable ohpserver
+
+
+# Installed
+echo '' > /root/.tcat_installed
+
+
+
 # finishing
 cd
 chown -R www-data:www-data /home/vps/public_html
 /etc/init.d/nginx restart
 /etc/init.d/openvpn restart
-/etc/init.d/cron restart
-/etc/init.d/ssh restart
-/etc/init.d/dropbear restart
-/etc/init.d/fail2ban restart
-/etc/init.d/stunnel4 restart
+ /etc/init.d/cron restart
+ /etc/init.d/ssh restart
+# /etc/init.d/dropbear restart
+# /etc/init.d/fail2ban restart
+# /etc/init.d/stunnel4 restart
 service squid restart
 # /etc/init.d/webmin restart
 
